# Generated by Django 2.0.7 on 2018-11-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiles',
            table='tiles',
        ),
    ]
