# Generated by Django 2.0.7 on 2018-11-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20181114_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiles',
            options={'managed': True, 'verbose_name_plural': 'tiles'},
        ),
    ]
