# Generated by Django 2.0.7 on 2018-11-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20181114_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiles',
            options={'managed': False, 'verbose_name_plural': 'tiles'},
        ),
    ]
